#!/usr/bin/env python3
"""
load_ecosystem.py — parse ECOSYSTEM.md tables + relationships.json into Cypher
MERGE statements that load the open* knowledge graph into Apache AGE.

Usage:
    # Print Cypher to stdout (review/diff)
    python3 scripts/load_ecosystem.py

    # Execute against a live AGE Postgres
    python3 scripts/load_ecosystem.py --dsn postgresql://postgres:postgres@localhost:5455/postgres

    # Load into a custom graph (default: open_star_graph)
    python3 scripts/load_ecosystem.py --dsn ... --graph my_graph

The output is idempotent: every node and edge uses MERGE, so re-running is safe.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
ECOSYSTEM_MD = REPO / "ECOSYSTEM.md"
RELATIONSHIPS_JSON = REPO / "ontology" / "relationships.json"

# Section letter (## A. ...) → category slug used in seed_concepts.json
SECTION_TO_CATEGORY: dict[str, str] = {
    "A": "languages",
    "B": "ai-ml",
    "C": "llm-agents",
    "D": "cloud-native",
    "E": "obs",
    "F": "data",
    "G": "security",
    "H": "os-firmware",
    "I": "web",
    "J": "devtools",
    "K": "desktop",
    "L": "additions",
}

# Section letter → primary stack layer slug (1–8). Best-effort default; specific
# project assignments are still done in relationships.json + load_extra_edges.
SECTION_TO_LAYER: dict[str, str] = {
    "A": "os-net",        # languages/runtimes sit at OS-level
    "B": "ai",
    "C": "ai",
    "D": "cloud",
    "E": "observability",
    "F": "data-gov",
    "G": "security",
    "H": "firmware",      # OS+firmware+EDA — leans firmware
    "I": "cloud",         # web frameworks deployed on cloud
    "J": "cloud",         # dev tools / CI
    "K": "ai",            # graphics/scientific often AI-adjacent
    "L": "cloud",         # mixed; see relationships.json for overrides
}

LINK_RE = re.compile(r"\[([^\]]+)\]\(([^)]+)\)")
SECTION_RE = re.compile(r"^##\s+([A-L])\.\s+", re.MULTILINE)
TABLE_ROW_RE = re.compile(
    r"^\|\s*(\d+)\s*\|\s*([^|]+?)\s*\|\s*([^|]+?)\s*\|\s*([^|]+?)\s*\|\s*([^|]+?)\s*\|\s*$"
)


@dataclass(frozen=True)
class Project:
    number: int
    name: str
    role: str
    license: str
    url: str
    section: str  # letter A–L

    @property
    def category(self) -> str:
        return SECTION_TO_CATEGORY.get(self.section, "uncategorized")

    @property
    def layer(self) -> str:
        return SECTION_TO_LAYER.get(self.section, "cloud")


def cypher_str(s: str) -> str:
    """Escape a string for a Cypher single-quoted literal."""
    return s.replace("\\", "\\\\").replace("'", "\\'")


def extract_url(cell: str) -> str:
    """Extract URL from a Markdown link cell like '[text](url)'."""
    m = LINK_RE.search(cell)
    return m.group(2) if m else cell.strip()


def parse_ecosystem(text: str) -> list[Project]:
    """Parse ECOSYSTEM.md content; yield one Project per table row."""
    sections: list[tuple[str, int]] = []
    for m in SECTION_RE.finditer(text):
        sections.append((m.group(1), m.start()))
    sections.append(("END", len(text)))

    projects: list[Project] = []
    for i in range(len(sections) - 1):
        letter, start = sections[i]
        _, end = sections[i + 1]
        chunk = text[start:end]
        for line in chunk.splitlines():
            m = TABLE_ROW_RE.match(line)
            if not m:
                continue
            num, name, role, lic, link = m.groups()
            url = extract_url(link)
            projects.append(
                Project(
                    number=int(num),
                    name=name.strip(),
                    role=role.strip(),
                    license=lic.strip(),
                    url=url,
                    section=letter,
                )
            )
    return projects


# ---------------------------------------------------------------------------
# Cypher generation
# ---------------------------------------------------------------------------

CYPHER_HEADER = """\
-- Generated by scripts/load_ecosystem.py — DO NOT EDIT MANUALLY
-- Re-run: python3 scripts/load_ecosystem.py [--dsn ...]
LOAD 'age';
SET search_path = ag_catalog, "$user", public;
"""


def cypher_for_project(p: Project, graph: str) -> str:
    is_oss = "false" if p.license.lower() in {"proprietary", ""} else "true"
    return (
        f"SELECT * FROM cypher('{graph}', $$\n"
        f"  MERGE (p:Project {{name: '{cypher_str(p.name)}'}})\n"
        f"    ON CREATE SET p.url = '{cypher_str(p.url)}',\n"
        f"                  p.role = '{cypher_str(p.role)}',\n"
        f"                  p.license = '{cypher_str(p.license)}',\n"
        f"                  p.section = '{p.section}',\n"
        f"                  p.is_oss = {is_oss}\n"
        f"$$) AS (r agtype);"
    )


def cypher_for_category(p: Project, graph: str) -> str:
    return (
        f"SELECT * FROM cypher('{graph}', $$\n"
        f"  MERGE (c:Category {{slug: '{p.category}'}})\n"
        f"  WITH c\n"
        f"  MATCH (p:Project {{name: '{cypher_str(p.name)}'}})\n"
        f"  MERGE (p)-[:BELONGS_TO]->(c)\n"
        f"$$) AS (r agtype);"
    )


def cypher_for_layer(p: Project, graph: str) -> str:
    return (
        f"SELECT * FROM cypher('{graph}', $$\n"
        f"  MATCH (p:Project {{name: '{cypher_str(p.name)}'}}),\n"
        f"        (l:StackLayer {{slug: '{p.layer}'}})\n"
        f"  MERGE (p)-[:RUNS_ON]->(l)\n"
        f"$$) AS (r agtype);"
    )


def cypher_for_edge(
    label: str,
    a: str,
    b: str,
    note: str | None,
    graph: str,
) -> str:
    props = ""
    if note:
        props = f" {{note: '{cypher_str(note)}'}}"
    return (
        f"SELECT * FROM cypher('{graph}', $$\n"
        f"  MATCH (a:Project {{name: '{cypher_str(a)}'}}),\n"
        f"        (b:Project {{name: '{cypher_str(b)}'}})\n"
        f"  MERGE (a)-[:{label}{props}]->(b)\n"
        f"$$) AS (r agtype);"
    )


def cypher_for_skill_edge(project: str, skill: str, graph: str) -> str:
    return (
        f"SELECT * FROM cypher('{graph}', $$\n"
        f"  MERGE (s:Skill {{name: '{cypher_str(skill)}'}})\n"
        f"  WITH s\n"
        f"  MATCH (p:Project {{name: '{cypher_str(project)}'}})\n"
        f"  MERGE (p)-[:TEACHES]->(s)\n"
        f"$$) AS (r agtype);"
    )


def cypher_for_foundation_edge(project: str, foundation: str, graph: str) -> str:
    return (
        f"SELECT * FROM cypher('{graph}', $$\n"
        f"  MERGE (f:Foundation {{name: '{cypher_str(foundation)}'}})\n"
        f"  WITH f\n"
        f"  MATCH (p:Project {{name: '{cypher_str(project)}'}})\n"
        f"  MERGE (p)-[:GOVERNED_BY]->(f)\n"
        f"$$) AS (r agtype);"
    )


def cypher_for_relationships(rels: dict, graph: str) -> list[str]:
    out: list[str] = []
    for e in rels.get("depends_on", []):
        out.append(cypher_for_edge("DEPENDS_ON", e["from"], e["to"], e.get("note"), graph))
    for e in rels.get("complements", []):
        out.append(cypher_for_edge("COMPLEMENTS", e["a"], e["b"], e.get("note"), graph))
    for e in rels.get("supersedes", []):
        out.append(cypher_for_edge("SUPERSEDES", e["from"], e["to"], e.get("note"), graph))
    for e in rels.get("merges_into", []):
        out.append(cypher_for_edge("MERGES_INTO", e["from"], e["to"], e.get("note"), graph))
    for e in rels.get("part_of", []):
        out.append(cypher_for_edge("PART_OF", e["child"], e["parent"], None, graph))
    for e in rels.get("teaches", []):
        out.append(cypher_for_skill_edge(e["project"], e["skill"], graph))
    for e in rels.get("governed_by", []):
        out.append(cypher_for_foundation_edge(e["project"], e["foundation"], graph))
    return out


def generate_cypher(
    projects: list[Project],
    rels: dict,
    graph: str = "open_star_graph",
) -> str:
    parts: list[str] = [CYPHER_HEADER, ""]
    parts.append("-- ============== Projects ==============")
    parts.extend(cypher_for_project(p, graph) for p in projects)
    parts.append("\n-- ============== Categories ==============")
    parts.extend(cypher_for_category(p, graph) for p in projects)
    parts.append("\n-- ============== Stack-layer assignments ==============")
    parts.extend(cypher_for_layer(p, graph) for p in projects)
    parts.append("\n-- ============== Inter-project + skill + foundation edges ==============")
    parts.extend(cypher_for_relationships(rels, graph))
    return "\n".join(parts) + "\n"


# ---------------------------------------------------------------------------
# Execution path
# ---------------------------------------------------------------------------


def execute_cypher(cypher: str, dsn: str) -> int:
    try:
        import psycopg
    except ImportError:
        print("psycopg not installed; install with: pip install psycopg[binary]", file=sys.stderr)
        return 2
    count = 0
    with psycopg.connect(dsn, autocommit=True) as conn:
        for stmt in cypher.split(";"):
            s = stmt.strip()
            if not s or s.startswith("--"):
                continue
            conn.execute(s + ";")
            count += 1
    return count


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    p.add_argument("--ecosystem", default=str(ECOSYSTEM_MD), help="ECOSYSTEM.md path")
    p.add_argument("--relationships", default=str(RELATIONSHIPS_JSON), help="relationships.json path")
    p.add_argument("--graph", default="open_star_graph", help="AGE graph name")
    p.add_argument("--dsn", help="If set, execute against this Postgres DSN; else print to stdout")
    args = p.parse_args(argv)

    text = Path(args.ecosystem).read_text()
    projects = parse_ecosystem(text)
    rels = json.loads(Path(args.relationships).read_text())
    cypher = generate_cypher(projects, rels, graph=args.graph)

    if args.dsn:
        n = execute_cypher(cypher, args.dsn)
        print(f"Executed {n} Cypher statements against graph '{args.graph}'", file=sys.stderr)
        return 0
    sys.stdout.write(cypher)
    return 0


if __name__ == "__main__":
    sys.exit(main())
